version: '3.4'

services:
 redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

  icache.api:
    image: ${DOCKER_REGISTRY-}icache
    build:
      context: .
      dockerfile: iCache.API/Dockerfile
